# build definition for function app

resources:
- repo: self
  clean: true
trigger:
  batch: true
  branches:
    include:
    - master

stages:
- stage: build
  jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'
    variables:
      BuildConfiguration: 'release'
    steps:
    - checkout: self

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '2.2.x'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration) --no-cache'
    
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: false
        projects: '**/EmailBugTracker.csproj'
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: false

    - task: PublishPipelineArtifact@0
      displayName: 'Publish build Artifact'
      inputs:
        targetPath: '$(build.artifactstagingdirectory)'
        artifactName: function

    - task: PublishPipelineArtifact@0
      displayName: 'Publish Artifact: Infrastructure Scripts'
      inputs:
        targetPath: deploy
        artifactName: deploy

- stage: release
  jobs:
  - job: infra
    pool:
      name: 'Hosted Windows 2019 with VS2019'
    variables:
    - group: 'Deployment Credentials'
    - name: ResourceGroupName
      value: 'email-bugtracker'

    steps:
    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: deploy
        targetPath: '$(System.ArtifactsDirectory)'

    - task: AzurePowerShell@4
      displayName: 'Deploy infrastructure'
      inputs:
        azureSubscription: 'Opensource Deployments'
        ScriptPath: '$(System.ArtifactsDirectory)/Deploy.ps1'
        ScriptArguments: '-ResourceGroupName $(ResourceGroupName)'
        azurePowerShellVersion: LatestVersion

  - job: deploy
    dependsOn: infra
    pool:
      name: 'Hosted Windows 2019 with VS2019'
    variables:
    - group: 'Deployment Credentials'
    - name: ResourceGroupName
      value: 'email-bugtracker'
    - name: DetermineTargetProjectVia
      value: Recipient
    - name: AuditContainerName
      # null if you wish to disable audit logging (captures full reports into a storage account incl. sender email)
      value : 'audit'

    steps:
    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: function
        targetPath: '$(System.ArtifactsDirectory)'

    - task: AzureFunctionApp@1
      displayName: 'Deploy Azure Function App'
      inputs:
        azureSubscription: 'Opensource Deployments'
        appType: functionApp
        appName: '$(ResourceGroupName)'
        appSettings: '-DetermineTargetProjectVia $(DetermineTargetProjectVia) -AuditContainerName $(AuditContainerName)'
        package: '$(System.ArtifactsDirectory)/EmailBugTracker'
        deploymentMethod: runFromPackage
